### ISSUE TITLE
Invalid Phishing URLs ?

### ISSUE THREAD

**Issue by JenoP** [rebl0x3r/URLer#1]
Hi,

A favor please..

With this Python script(url.py), I generated a list of Phishing URLs. Some of the URLs given below.
Issue: While accessing them in latest Chrome, got timed-out. Are those URLs valid ? 

https://www.30nnect-st4blc.ddns.net
https://www.1_s3cvre-4pj.ddns.net
https://www.d0nn3ct-trvstec.ddns.net
https://www.dt4bl3-trvstes.ddns.net
https://www.3ess10n-st4bls.ddns.net
https://www.h0c4l-otl.ddns.net
https://www.3erver-secvrs.ddns.net
https://www.t4f3-svpp0rs.ddns.net
https://www.t3rver-pr0tecs.ddns.net

**Comment by rebl0x3r** [comment]
These links are just generated and not valid. If you want them to get valid, you have register them on a DNS like no ip .
