### ISSUE TITLE
I do not know what to do

### ISSUE THREAD

**Issue by CristianMB2255** [rebl0x3r/URLer#2]
![image](https://user-images.githubusercontent.com/84812535/149853645-f3639706-007e-4fdd-af74-9dc4309e99b4.png)

**Comment by rebl0x3r** [comment]
Type `h` or `?` for the help usage.

**Comment by CristianMB2255** [comment]
> Type `h` or `?` for the help usage.

`h`

**Comment by rebl0x3r** [comment]
> > Type `h` or `?` for the help usage.
> 
> `h`

Both works.
